# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: trusty

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4 # give xvfb some time to start

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - devtools

warnings_are_errors: false

# r_github_packages:
#  - r4ss/r4ss
